--- 
networks: 
  main: 
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.30.255.0/24
      driver: default
services: 
  nats-streaming-1: 
    command: 
      - "--cluster_id"
      - nats-streaming
      - "--store"
      - file
      - "--dir"
      - /data/msg
      - "--clustered"
      - "--cluster_bootstrap"
      - "--cluster_node_id"
      - nats-streaming-1
      - "--cluster_log_path"
      - /data/log
      - "--cluster_raft_logging"
      - "--stan_debug"
      - "--stan_trace"
      - "--port"
      - "4222"
      - "--http_port"
      - "8222"
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:5222"
      - "--hb_interval"
      - 2s
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - 5s
    image: "nats-streaming:0.16.2"
    ports: 
      - "14222:4222"
      - "18222:8222"
    volumes: 
      - "./nats-streaming-1:/data"
  nats-streaming-2: 
    command: 
      - "--cluster_id"
      - nats-streaming
      - "--store"
      - file
      - "--dir"
      - /data/msg
      - "--clustered"
      - "--cluster_node_id"
      - nats-streaming-2
      - "--cluster_log_path"
      - /data/log
      - "--cluster_raft_logging"
      - "--stan_debug"
      - "--stan_trace"
      - "--port"
      - "4222"
      - "--http_port"
      - "8222"
      - "--debug"
      - "--routes"
      - "nats://nats-streaming-1:5222"
      - "--cluster"
      - "nats://0.0.0.0:5222"
      - "--hb_interval"
      - 2s
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - 5s
    image: "nats-streaming:0.16.2"
    ports: 
      - "24222:4222"
      - "28222:8222"
    volumes: 
      - "./nats-streaming-2:/data"
  nats-streaming-3: 
    command: 
      - "--cluster_id"
      - nats-streaming
      - "--store"
      - file
      - "--dir"
      - /data/msg
      - "--clustered"
      - "--cluster_node_id"
      - nats-streaming-3
      - "--cluster_log_path"
      - /data/log
      - "--cluster_raft_logging"
      - "--stan_debug"
      - "--stan_trace"
      - "--port"
      - "4222"
      - "--http_port"
      - "8222"
      - "--debug"
      - "--routes"
      - "nats://nats-streaming-1:5222"
      - "--cluster"
      - "nats://0.0.0.0:5222"
      - "--hb_interval"
      - 2s
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - 5s
    image: "nats-streaming:0.16.2"
    ports: 
      - "34222:4222"
      - "38222:8222"
    volumes: 
      - "./nats-streaming-3:/data"
version: "3.7"
